name: V2ex

on:
  schedule:
    # 可自定义 cron 表达式
    - cron: '0 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jinfagang/arxiv_action@0.1
        with:
          webhook: ${{ secrets.WEBHOOK }}
          secret: ${{ secrets.SECRET }}
          count: 8
